# Generated by Django 2.1 on 2018-09-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0002_auto_20180831_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anilist_username',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mal_username',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfc_username',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
