# Generated by Django 2.1 on 2018-08-28 01:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPG', keep_meta=True, null=True, quality=0, size=[256, 256], upload_to='avatar'),
        ),
    ]
