# Generated by Django 2.1 on 2018-09-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0003_auto_20180901_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=20000),
        ),
    ]
