# Generated by Django 2.1 on 2018-09-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0004_auto_20180905_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nsfw_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
