# Generated by Django 2.1 on 2018-08-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0004_auto_20180828_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'verbose_name_plural': 'forum categories'},
        ),
    ]
