# Generated by Django 2.1 on 2018-09-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0006_post_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_reason',
            field=models.TextField(default=''),
        ),
    ]
