# Generated by Django 2.1 on 2018-08-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0006_auto_20180828_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcategory',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
