# Generated by Django 2.0.8 on 2018-09-07 15:07

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0008_post_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
