# Generated by Django 2.0.8 on 2018-09-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0010_auto_20180907_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='only_staff_can_post',
            field=models.BooleanField(default=False),
        ),
    ]
