# Generated by Django 2.0.8 on 2018-09-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0011_forum_only_staff_can_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_sticky',
            field=models.BooleanField(default=False),
        ),
    ]
