# Generated by Django 2.0.8 on 2018-09-22 11:36

import FigureSite.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0014_forum_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=0, size=[128, 128], upload_to=FigureSite.models.ForumIconRename()),
        ),
    ]
