# Generated by Django 2.0.8 on 2018-09-26 10:13

import FigureSite.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0015_auto_20180922_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='FigureSite.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=80)),
                ('icon', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=0, size=[32, 32], upload_to=FigureSite.models.VoteTypeRename())),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('creator', 'post')},
        ),
        migrations.AddField(
            model_name='uservote',
            name='vote_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='FigureSite.VoteType'),
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('user', 'post')},
        ),
    ]
