# Generated by Django 2.0.8 on 2018-10-29 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0018_auto_20181029_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_reason', models.TextField(max_length=1000)),
                ('ban_expiry_date', models.DateTimeField(editable=False)),
                ('banned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_bans', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='FigureSite.Post')),
            ],
        ),
    ]
