# Generated by Django 2.0.8 on 2018-09-29 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0018_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_users',
            field=models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
