# Generated by Django 2.0.8 on 2018-10-07 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0018_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_actor',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_object_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_object_type',
            new_name='object_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='thread',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_thread', to=settings.AUTH_USER_MODEL),
        ),
    ]
