# Generated by Django 2.0.8 on 2018-10-07 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0019_auto_20181007_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
