# Generated by Django 2.0.8 on 2018-10-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0020_auto_20181007_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_expiry_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(default='', max_length=200),
        ),
    ]
