# Generated by Django 2.0.8 on 2018-11-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0021_auto_20181111_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=40000),
        ),
    ]
