# Generated by Django 2.0.8 on 2018-10-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0021_auto_20181012_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ban_reason',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(default='', max_length=400),
        ),
    ]
