# Generated by Django 2.0.8 on 2019-01-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0023_auto_20181126_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
