# Generated by Django 2.0.8 on 2019-01-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0023_auto_20181126_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFCItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('title', models.TextField()),
                ('manufacturer', models.CharField(max_length=300)),
                ('mfc_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='related_items',
            field=models.ManyToManyField(related_name='related_threads', to='FigureSite.MFCItem'),
        ),
    ]
