# Generated by Django 2.0.8 on 2019-01-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0024_thread_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFCItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'permissions': (('change_threads_subscription', 'Change subscription status in forum'), ('move_threads', 'Move threads in forum'), ('make_threads_nsfw', 'Make thread be NSFW in forum'), ('create_threads', 'Create threads in forum'), ('view_forum', 'View forum'))},
        ),
        migrations.AddField(
            model_name='thread',
            name='related_items',
            field=models.ManyToManyField(related_name='related_threads', to='FigureSite.MFCItem'),
        ),
    ]
