# Generated by Django 2.0.8 on 2019-01-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0024_auto_20190110_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfcitem',
            name='mfc_id',
        ),
    ]
