# Generated by Django 2.0.8 on 2019-01-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0025_remove_mfcitem_mfc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfcitem',
            name='manufacturer',
        ),
    ]
