# Generated by Django 2.1.5 on 2020-05-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0026_auto_20190715_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
