# Generated by Django 2.0.8 on 2019-01-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FigureSite', '0027_auto_20190117_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'permissions': (('change_threads_subscription', 'Change subscription status in forum'), ('move_threads', 'Move threads in forum'), ('make_threads_nsfw', 'Make thread be NSFW in forum'), ('create_posts', 'Create post in forum'))},
        ),
    ]
