"""
Django settings for figurabackend project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import datetime
from .shared_settings import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
with open('/etc/secret_key.txt') as f:
    SECRET_KEY = f.read().strip()

with open('/etc/mail_password.txt') as f:
    EMAIL_HOST_PASSWORD = f.read().strip()
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'hobbyfiguras.moe']


# SECURITY WARNING: keep the secret key used in production secret!
with open('/etc/hashid_secret.txt') as f:
    HASHID_FIELD_SALT = f.read().strip()

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'figuresite',
        'USER': 'figuresite'
    }
}

ACCOUNT_EMAIL_SUBJECT_PREFIX = 'Hobbyfiguras - '

MEDIA_ROOT='/server/live/media'
STATIC_ROOT='/server/live/static'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = '127.0.0.1'
EMAIL_HOST_USER = 'Hobbyfiguras <noreply@hobbyfiguras.moe>'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'noreply@hobbyfiguras.moe'